#Defines if tools will have their special characteristic (aka power), like tin's drop duplication
"Tool Powers" = true
#Defines if weapons will have their special characteristic (aka power), like tin's drop duplication
"Weapons Powers" = true
#Defines if armors will have their special characteristic (aka power), like platinum's strength II effect
"Armors Powers" = true
#Progress changes from [ Stone -> Iron ] to [ Stone -> Tin ->  Iron ]. Can be further adjusted via 'orevolution:tools/tin_progress_followers' tag
"Tin progression" = true
#Progress changes from [ Iron -> Diamond ] to [ Iron -> Platinum ->  Diamond ]. Can be further adjusted via 'orevolution:tools/platinum_progress_followers' tag
"Platinum progression" = true

