
[gameplay]
	#Display the text 'You can't harvest this block yet!'
	warn_ore = true

[tooltips]
	#Display the 'Harvest tier' tooltip on all tiered tools
	harvest_tip = true
	#Display the 'power' tooltip on all tools that have one
	tools_powers_tip = true
	#Display the 'power' tooltip on all weapons that have one
	weapons_powers_tip = true
	#Display the 'power' tooltip on all armors that have one
	armors_powers_tip = true
	#Display the 'Tin tier' tooltip on all stone-tiered tools
	tin_prog_tip = true
	#Display the 'Platinum tier' tooltip on all iron-tiered tools
	plat_prog_tip = true

